


 时间 2018-05-30 16:00:14.4121 
 消息内容 requestLog
{"URI":"/api/Values","ElapsedTime":26509.946900000003,"Method":"POST","RequestParams":"7777","QueryString":"","Result":"{\"Code\":500,\"SubCode\":\"unknow-error\",\"Msg\":\"系统繁忙！\"}","Status":200,"Headers":{"Connection":["keep-alive"],"Content-Length":["4"],"Content-Type":["application/json"],"Accept":["application/json"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["zh-CN,zh;q=0.9"],"Host":["localhost:29162"],"Referer":["http://localhost:29162/swagger/ui/index"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"],"Origin":["http://localhost:29162"]},"ChildrenRequests":{},"DBLogs":[],"Exception":"Message:未将对象引用设置到对象的实例。\r\nStackTrace   在 MF.Core.ApiResponsePager`1..ctor(IPagedList`1 pagerData)\r\n   在 WebTest2.Controllers.ValuesController.Post(String value) 位置 D:\\源码\\Allen\\MF\\Tests\\WebTest2\\Controllers\\ValuesController.cs:行号 38\r\n   在 lambda_method(Closure , Object , Object[] )\r\n   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__3(Object instance, Object[] methodParameters)\r\n   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()"}
 线程ID 17 
